CREATE DATABASE SISGIM
GO

USE SISGIM
GO

CREATE TABLE INSTRUMENTOMUSICAL
(
	CODIGO INT PRIMARY KEY NOT NULL,
	NOMBRE VARCHAR(200) NOT NULL,
	DESCRIPCION VARCHAR(500),
	UBICACION VARCHAR(100),
	NOMBREPROFESOR NVARCHAR(256)
);
GO

CREATE TABLE PRESTAMO
(
	ID INT PRIMARY KEY NOT NULL IDENTITY,
	FECHAHORAPRESTAMO DATETIME NOT NULL,
	FECHAHORADEVOLUCION DATETIME,
	NOMBREALUMNO VARCHAR(200) NOT NULL,
	CURSOALUMNO VARCHAR(10) NOT NULL,
	NOMBREPROFESOR NVARCHAR(256),
	CODIGOINSTRUMENTO INT FOREIGN KEY REFERENCES INSTRUMENTOMUSICAL (CODIGO)
);
GO

