CREATE DATABASE SISGIM2
GO

USE SISGIM2
GO

CREATE TABLE TIPO_INSTRUMENTO
(
	CODIGO VARCHAR(50) PRIMARY KEY NOT NULL,
	DESCRIPCION VARCHAR(150) NOT NULL
);
GO

CREATE TABLE UBICACION
(
	CODIGO VARCHAR(50) PRIMARY KEY NOT NULL,
	DESCRIPCION VARCHAR(150) NOT NULL
);
GO

CREATE TABLE INSTRUMENTO
(
	CODIGO VARCHAR(100) PRIMARY KEY NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	MARCA VARCHAR(50) NOT NULL,
	MODELO VARCHAR(50) NOT NULL,
	FK_UBICACION VARCHAR(50) FOREIGN KEY REFERENCES UBICACION (CODIGO),
	FK_TIPO_INSTRUMENTO VARCHAR(50) FOREIGN KEY REFERENCES TIPO_INSTRUMENTO (CODIGO),
	DESCRIPCION VARCHAR(150),
	TAGS VARCHAR(150),
	DISPONIBLE BIT NOT NULL
);
GO

CREATE TABLE TIPO_PERSONA
(
	CODIGO VARCHAR(50) PRIMARY KEY NOT NULL,
	DESCRIPCION VARCHAR(150)
);
GO

CREATE TABLE CURSO
(
	CODIGO VARCHAR(15) PRIMARY KEY NOT NULL,
	GRADO VARCHAR(10) NOT NULL,
	LETRA VARCHAR(3) NOT NULL
);
GO

CREATE TABLE PERSONA
(
	RUN INT PRIMARY KEY NOT NULL,
	DV VARCHAR(1) NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	APP VARCHAR(50) NOT NULL,
	APM VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	CONTRASENA VARCHAR(50) NOT NULL,
	FK_TIPO_PERSONA VARCHAR(50) FOREIGN KEY REFERENCES TIPO_PERSONA (CODIGO),
	FK_CURSO VARCHAR(15) FOREIGN KEY REFERENCES CURSO (CODIGO)
);
GO

CREATE TABLE TIPO_MOVIMIENTO
(
	CODIGO VARCHAR(50) PRIMARY KEY NOT NULL,
	TIPO VARCHAR(20) NOT NULL,
	DESCRIPCION VARCHAR(30)
);
GO

CREATE TABLE MOVIMIENTO
(
	ID VARCHAR(150) PRIMARY KEY NOT NULL,
	FECHA DATETIME NOT NULL,
	FK_TIPO_MOVIMIENTO VARCHAR(50) FOREIGN KEY REFERENCES TIPO_MOVIMIENTO (CODIGO),
	FK_INSTRUMENTO VARCHAR(100) FOREIGN KEY REFERENCES INSTRUMENTO (CODIGO),
	FK_RUN_PRESTADOR INT FOREIGN KEY REFERENCES PERSONA (RUN),
	FK_RUN_USUARIO INT FOREIGN KEY REFERENCES PERSONA (RUN)
);
GO

